# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Combinestagram_04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Combinestagram_04

  target 'Combinestagram_04Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Combinestagram_04UITests' do
    # Pods for testing
  end

end
