# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wundercast_12' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wundercast_12
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'

  target 'Wundercast_12Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Wundercast_12UITests' do
    # Pods for testing
  end

end
