# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OurPlanet_10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OurPlanet_10
  pod 'RxSwift', '5.1.1'

  target 'OurPlanet_10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OurPlanet_10UITests' do
    # Pods for testing
  end

end
