# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickTodo_25' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickTodo_25
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'RxDataSources', '~> 4.0'

  # Community projects
  pod 'Action', '~> 4.0'
  pod 'NSObject+Rx', '~> 5.1'
  
  # Realm database
  pod 'RealmSwift', '~> 5.0'
  pod 'RxRealm', '~> 3.0'


end
