# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Observable_02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Observable_02
	pod 'RxSwift', '6.1.0'
	pod 'RxCocoa', '6.1.0'  

  target 'Observable_02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Observable_02UITests' do
    # Pods for testing
  end

end
