# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Transfrom_07' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Transfrom_07
  pod 'RxSwift', '5.1.1'
  pod 'RxRelay', '5.1.1'

  target 'Transfrom_07Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Transfrom_07UITests' do
    # Pods for testing
  end

end
