# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitFeed_08' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitFeed_08
  pod 'RxSwift', '5.1.1'
  pod 'RxRelay', '5.1.1'

  target 'GitFeed_08Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitFeed_08UITests' do
    # Pods for testing
  end

end
