use_frameworks!
inhibit_all_warnings!

abstract_target 'TweetieAbstract' do
  pod 'Alamofire'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'Unbox'
  pod 'Then'
  pod 'Reachability'
  pod 'RxRealmDataSources'

  target 'Tweetie_24' do
      platform :ios, '14.0'
      pod 'RxDataSources'
  end

end

post_install do |installer|
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
end
end
