# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '03_Subject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 03_Subject
  pod 'RxSwift', '6.1.0'
	pod 'RxCocoa', '6.1.0'

end
